# Dockerfile.production

FROM 614358145679.dkr.ecr.ap-south-1.amazonaws.com/wealthyalpine:node19.8.1

MAINTAINER somit srivastava "corp@wealthy.in"

ENV PROJECT_DIR=/opt/wealthy/app

ENV LOG_DIR=/var/log/wealthy/app

WORKDIR $PROJECT_DIR

# setup all the configfiles

COPY . $PROJECT_DIR/

EXPOSE 9000
EXPOSE 80

CMD ["sh","./secret_entrypoint.sh"]
CMD ["npm", "run", "start:prod"]